### ISSUE TITLE
}bedrock.hier.unwind not unwinding components of the nominated consolidation

### ISSUE THREAD

**Issue by AdamxDavis** [cubewise-code/bedrock#101]
**Describe the bug**
When unwind from a consolidation, recursively. The direct components of the nominated consolidation were not being unwound. The ancestors of the nominated consolidation are being unwound.

**To Reproduce**
Steps to reproduce the behaviour:
Example
  pDim = 'FIN OCoA' ;
  pHier = ''
  pConsol = 'Balance Sheet'
  Recursive = 1
  pDelim = '&'

**Expected behavior**
All the ancestors of the nominated consolidation including the components of the nominated consolidation should be unwound when recurcively

**Screenshots**

**Version**
PA 2.0.9

**Additional context**
The problem was when assigning the attribute to the ancestors the process was not assigning the attribute to nominated consolidation, see line Prolog:148. In the metadata tab the process breaking the components for the ansestors of the consolidation, Metadata:26. Because the nominated consolidation was not identified in the prolog the components where not being processed.

In the prolog:148 I added a test to for the nominated consolidation.
      If( ElementIsAncestor( pDim, pHier, pConsol, sElement ) = 1 % sElement @= pConsol);

**Comment by AdamxDavis** [comment]
Corrected process:
[}bedrock.hier.unwind.zip](https://github.com/cubewise-code/bedrock/files/3709457/bedrock.hier.unwind.zip)

**Comment by lotsaram** [comment]
@AdamxDavis there were some bugs with this process whihc were fixed just recently in #99 
Did you pull the latest version? As I think this fix is probably redundant.

**Comment by AdamxDavis** [comment]
It was not based on the latest. I will pull that version and re-test.

Regards

Adam
________________________________

**Comment by lotsaram** [comment]
@AdamxDavis pls re-open if it turns out not to be fixed but pretty sure it is.
