### ISSUE TITLE
}bedrock.hier.import dissociate elements that contain minus in principal name

### ISSUE THREAD

**Issue by AdamxDavis** [cubewise-code/bedrock#102]
**Describe the bug**
Elements that contained '-' are being dissociate on import.

**To Reproduce**
Steps to reproduce the behaviour:
Export to file a dimension that include elements with the principal name containing a '-' using }bedrock.hier.export.
Import the file using }bedrock.hier.import. 
Compare the elements to the original dimension and you will find elements that have a '-' shorten in the new dimension.

**Expected behaviour**
For a new dimension, the target dimension should be the same as the source dimension

**Screenshots**
None

**Version**
PA 2.0.9 

**Additional context**
I have fixed this issue by removing the scan function lines M:23 and D:18. 
[}bedrock.hier.import.zip](https://github.com/cubewise-code/bedrock/files/3710693/bedrock.hier.import.zip)

**Comment by lotsaram** [comment]
@AdamxDavis this one is very very weird to me. I wend back and checked the v3 archive and it doesn't come from there and I cant see any reason why any of the Scan and split after minus sign is happening for any of the variables. Makes no sense to me at all. I don't remember who developed the process to ask them what they were smoking.

To make it easy to integrate fixes please don't attach a file. Please do a pull request instead. It makes it much easier to merge in with no extra rework.

**Comment by AdamxDavis** [comment]
It appears to me that the information was added to make it human readable.

The scan complements the }bedrock.hier.export. There appears to be additional information attached to the value. It appears to me that it is not used in column 2. Hence the change.

I didn’t investigate if the additional information is used on import. Or that the value could be workout from other information in the record. Or if the data could be it’s own column. The easy fix would be to use a delimiter that is not used in dimension.

I will look at the pull request. It really should be my first step to resolving problem with the process.

Regards

Adam
________________________________

**Comment by lotsaram** [comment]
I just finished looking at the export process and came to the same conclusion.
The issue in the import is also that there is no handling for if the file is in "legacy" v3 format. It just assumes the new format on metadata and data (which would be bad for negative element weight or attributes with minus in the text if in v3 format). 
So I think the better fix would be 1/ the fix you already did to remove the scen from the element itself and then 2/ for rest of sVarN variables If( pLegacy <> 1, do the scan, = vN)
