### ISSUE TITLE
Use of ItemReject on Prolog

### ISSUE THREAD

**Issue by rclapp** [cubewise-code/bedrock#11]
https://github.com/cubewise-code/bedrock/blob/master/Bedrock.Cube.View.Publish.pro and other similar processes should be updated to use LogOutPut and ProcessBreak instead of ItemReject. ItemReject used outside the data/metadata tabs can have unintended consequences.

**Comment by lotsaram** [comment]
Hi @rclapp there won't be any changes to bedrock 3 but bedrock 4 is coming which will offer full support for TM1 v11 & hierarchies. There are a number of changes e.g. no more debug outputs . When we release v4 the plan is for much more open contribution her on github from any interested developers.
(The main hold-up right now to getting this out is not so much the overhaul of the library but rather bugs in TM1 hierarchy TI functions and MDX views which IBM needs to fix before it becomes usable).
