### ISSUE TITLE
Add support for ViewExtractSkipConsolidatedStringsSet in }bedrock.view.create and dependent processes

### ISSUE THREAD

**Issue by PiotrRajtar** [cubewise-code/bedrock#113]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to include C-level string values in view extracts using Bedrock processes as function **[ViewExtractSkipConsolidatedStringsSet](https://www.ibm.com/support/knowledgecenter/en/SSD29G_2.0.0/com.ibm.swg.ba.cognos.tm1_ref.2.0.0.doc/r_tm1_ref_tifun_viewextractskipconsolidatedstringsset.html)** is not implemented.
This is not commonly used, but there are some cases when you would want to copy all N-level numerics and all N-level and C-level strings (e.g. in version copy).

**Describe the solution you'd like**
Add a parameter **pSuppressConsolStrings** to }bedrock.view.create and all the dependant processes to leverage this function.
This might also mean changing the current behaviour of replacing C-level elements with all their leaves if pSuppressConsol=1, this should only really happen if pSuppressConsolStrings=1 as well. Need to consider backwards compatibility impact.

**Describe alternatives you've considered**
This can be worked around but requires extra manipulation of the view and subsets, ViewExtractSkipConsolidatedStringsSet would be cleaner.

**Comment by lotsaram** [comment]
done in #124
