### ISSUE TITLE
Add support for fixed dimension mapping in cube.loadfromfile

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/bedrock#116]
**Is your feature request related to a problem? Please describe.**
data.copy.intercube allows for fixed mappings for extra dimensions not present in the source but present in the target. The cube.loadfromfile process should also support this feature.

**Comment by lbrowncubewise** [comment]
I believe this issue can be closed, the desired outcome can be used with the }bedrock.cube.dimension.add process, however, it would be good to incorporate this within the process so it can all be done as one step?

**Comment by lotsaram** [comment]
done in #124
