### ISSUE TITLE
Bedrock Cube Data Import map new dimension

### ISSUE THREAD

**Issue by lbrowncubewise** [cubewise-code/bedrock#117]
**Is your feature request related to a problem? Please describe.**
It is always a pain when migrating data between cubes of different dimensionality I cannot use a bedrock process to import, for example when building a new cube with an additional dimension, I can export the data, but then have to create a new process to import the data because of the additional dimension, this functionality appears to be available in the intercube process but not the import.

**Describe the solution you'd like**
It would be great if the bedrock import process would give us the option to map a new dimension with a static value, i.e. the target cube has different dimentionality from the source cube, but loading would be against a single element.

**Describe alternatives you've considered**
The only alternative at present is a custom Temp process

**Additional context**

**Comment by lotsaram** [comment]
duplicate #116
