### ISSUE TITLE
}bedrock.cube.data.copy.intercube - Ability to run via File transfer

### ISSUE THREAD

**Issue by lbrowncubewise** [cubewise-code/bedrock#118]
**Is your feature request related to a problem? Please describe.**
At present the intercube process is great for smaller cubes, but stuggles with larger cube transfers because of either locking or calcing runs and can cause an issue with Wait locks.

**Describe the solution you'd like**
It would be nice to have an option to run the intercube process via file export and import to remove an issues of wait locking or the process running longer, this would make the process work for both scenarios.

**Describe alternatives you've considered**
At present the only alternative is to use bedrock export and import processes respectively

**Additional context**

**Comment by lotsaram** [comment]
done in #124
Same enhancement also added to }bedrock.cube.data.copy
