### ISSUE TITLE
Dim Clone blank target

### ISSUE THREAD

**Issue by iansdigby** [cubewise-code/bedrock#122]
**Describe the bug**
Bedrock 4 bug: }Bedrock.Dim.Clone
If you pass a blank to the pTgtDim parameter, it can create a dim with a huge name (and corresponding .dim file) called [Original Dim Name]_Clone_Clone_Clone..........
The one I got was too long a name  to delete in the file system (FAT32?). Could delete from TM1 though.
**To Reproduce**
1. Go to process '...'
2. Run with parameters '....'
3. Result is '...'

**Expected behavior**

**Screenshots**

**Version**
 - OS: [e.g. Windows Server 2106]
  - TM1 Server Version: [e.g. 11.4]

**Additional context**

**Comment by lotsaram** [comment]
Can't replicate this. In the scenario you describe the process creates a new dimension named <source dim>_clone which is the expected behaviour.
If you can reliably reproduce this then you need to be A LOT more specific about how to reproduce.
