### ISSUE TITLE
}bedrock.cube.data.clear.pro

### ISSUE THREAD

**Issue by mdegiovanni** [cubewise-code/bedrock#127]
The current process is ignoring pCubeLogging = 2 on Prolog, line 180.
So, the process finish with Processbreak;

**To Reproduce**
1. Go to process '}bedrock.cube.data.clear.pro'
2. Run with parameters 'pCubeLogging = 2'
3. Result is 'ProcessBreak'

**Expected behavior**
Just finish with no error, or break and no logging on cube involved.

**Screenshots**

**Version**
  - TM1 Server Version: [PA 2.0]

**Additional context**
What we have now in the process:
If( pCubeLogging <> 0 & pCubeLogging <> 1);
What I understand we need:
If( pCubeLogging <> 0 & pCubeLogging <> 1 & pCubeLogging <> 2);

**Comment by lotsaram** [comment]
@mdegiovanni yes your fix looks correct. Do you want to submit a pull request to fix the issue?

**Comment by mdegiovanni** [comment]
Yes, please.
I'm trying now, but I still cannot do it properly
