### ISSUE TITLE
Cube.View.Create - Allow 'pFilter' to contain elements with spaces

### ISSUE THREAD

**Issue by JimmyKer** [cubewise-code/bedrock#13]
Hi,

I've elements with a space inside, instead off creating another alias, i've added following change to the prolog:

Old Code:
```
    # Ignore spaces
    IF (TRIM(sChar) @<> '' );

      ### Dimension Name ###
```
New Code:
```
    # Ignore spaces
    IF (TRIM(sChar) @<> '' );
	
      # Convert special character in element to 
space - todo make this character a parameter
      IF ( sChar @= '§' ) ;
        sChar = ' ' ;
      ENDIF;

      ### Dimension Name ###
```

Kind regards,
Jimmy

**Comment by lotsaram** [comment]
Hi @JimmyKer 
I can't see why there's any need to do this. TM1 is case and space insensitive.
So as far as TM1 is concerned  'this element' @= 'ThisElement' @= 'tH    IsE  l e m  eNt', ... etc.
The reason spaces are removed is they make no difference to setting the filter. What is your requirement for wanting to include them?

**Comment by JimmyKer** [comment]
Didn't know that, learned something new today, thx
