### ISSUE TITLE
All bedrock processes are deleted when running process "Bedrock.Server.LogFile.Delete"

### ISSUE THREAD

**Issue by reecethomson** [cubewise-code/bedrock#14]
In Prolog Tab

Current Code (deletes all Bedrock Processes) :(
  ASCIIOUTPUT( sFileName, 'forfiles -p "'| pLogDir |'" -s -m Bedrock*.* -d -' | sBedrockDays | ' -c "cmd /c del @path"' );

New Code (Only deletes Bedrock .debug files) :)
  ASCIIOUTPUT( sFileName, 'forfiles -p "'| pLogDir |'" -s -m Bedrock*.debug -d -' | sBedrockDays | ' -c "cmd /c del @path"' );

Cheers

**Comment by lotsaram** [comment]
In v4 there won't be any debug files so I don't have any plans to fix this. But if you want to create a pull request I'm happy to merge the change in.
On a side note: you are saying you didn't have LoggingDirectory set in tm1s.cfg and were using the data directory as the logs directory? (Shame on you :-o)

**Comment by reecethomson** [comment]
Gee that was a quick response!!!!

Only discovered it by accident doing some demo work. Never bothered to set a logging directory for something I end up deleting.

I hear version 4 is good. Looking forward to seeing it.

Now that I have created a profile I promise to contribute to the community.

Have a good one.

R
