### ISSUE TITLE
}bedrock.cube.data.copy documentation is missing pFile

### ISSUE THREAD

**Issue by PiotrRajtar** [cubewise-code/bedrock#149]
**Describe the bug**
}bedrock.cube.data.copy [Wiki documentation](https://github.com/cubewise-code/bedrock/wiki/%7Dbedrock.cube.data.copy) has not been updated to reflect the latest updates to the process.

**Expected behavior**
It seems the the documentation pages need to be updated periodically or ideally after a significant pull request is approved.

**Comment by lotsaram** [comment]
Yes updating the documentation wiki pages is currently a manual process. (Well it is automated via a script that reads the md within the DocString tags and creates the wiki, but it is a manual process to both run the script and push the updates to the wiki git).

**Comment by lotsaram** [comment]
we just updated the wiki
