### ISSUE TITLE
 }bedrock.cube.data.copy to allow Export out and Import in

### ISSUE THREAD

**Issue by tatwong** [cubewise-code/bedrock#158]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
When doing data read and CellPutN on the same TI, sometimes TM1 perform very slow, tested in some case could be over 100 times slower, few seconds vs 20 minutes to load the same data set.

**Describe the solution you'd like**
A parameter to allow instead of doing data read and write on the same TI, it triggers  a file to be exported and import the exported files back into TM1 behind the scene to speed up the overall performance.
Similar requirement for  }bedrock.cube.data.copy.intercube as well.
Even better it may delete the exported files after the completion of this TI for both Windows and Linux environment.

**Comment by lotsaram** [comment]
Are you using a recent version? Becasue I think what you are requesting already exists https://github.com/cubewise-code/bedrock/wiki/%7Dbedrock.cube.data.copy see the pFile parameter.
