### ISSUE TITLE
All bedrock export processes should support non-ASCII characters

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/bedrock#159]
**Is your feature request related to a problem? Please describe.**  
Currently all }bedrock.X.export processes are using AsciiOutput and are therefore limited to ASCII characters. Any non-ASCII characters are converted to "?" by AsciiOutput function.

**Describe the solution you'd like**  

1. convert all }bedrock.X.export processes to use TextOutput in place of AsciiOutput function  
2. introduce a new parameter _pCharacterSet_ in all }bedrock.X.export processes to set the output character set with the SetOutputCharacterSet function. The default character set if the parameter is not supplied or is empty should be TM1CS_UTF8

Likewise all }bedrock.X.import processes should also have _pCharacterSet_ parameter added in order to be able to set the import character set.

**Comment by lotsaram** [comment]
@tatwong @payion  was there any need to also set the character set in the import processes or did it just work as is? (e.g. can we close this already?)

**Comment by payion** [comment]
Hi @lotsaram ,

No, don't need to change the import process.
