### ISSUE TITLE
Handling of Unicode when export and import using Bedrock

### ISSUE THREAD

**Issue by tatwong** [cubewise-code/bedrock#160]
**Describe the bug**
We have some data that need to be exported and imported back to TM1, some of our characters are unicode, seems like at the moment, it would export a "?" character out.

![image](https://user-images.githubusercontent.com/43463864/81282489-cd74e500-908d-11ea-9359-7d757300ab11.png)

**To Reproduce**
1. Have a cube that store a "✓" character.
2. Execute bedrock process to export data from this cube.
3. The "✓" sign will become "?"

**Expected behavior**
The "✓" character would be exported.

**Version**
 - OS: [Windows Server 2106]
  - TM1 Server Version: [PA 2.0.8]

**Comment by lotsaram** [comment]
duplicate #159
