### ISSUE TITLE
}bedrock.cube.data.import always returns error

### ISSUE THREAD

**Issue by rderenato** [cubewise-code/bedrock#173]
**Describe the bug**
The '}bedrock.cube.data.import' is always returning an error 'cannot convert string to a real number on PROLOG line (148) and (167)

**To Reproduce**
1. Go to process '}bedrock.cub.data.export' and export any cube view
2. Go to process '}bedrock.cub.data.import' and now import the previously exported cube view
3. The process will run and upload the data correctly, but will always return the error:
'Prolog procesdure line (148): Cannot convert string "," to a real number'
'Prolog procesdure line (167): Cannot convert string """ to a real number'

**Expected behavior**
The data should be loaded with no errors

**Screenshots**
![Error Bedrock import](https://user-images.githubusercontent.com/61034574/82509953-a669e900-9b4c-11ea-999f-036eb177b5a6.jpg)

**Version**
 - OS: Windows 7 Enterprise
  - PA 2.0

**Additional context**

**Comment by lotsaram** [comment]
@rderenato please pull the latest version with a fix for this issue
