### ISSUE TITLE
pZeroSource in }bedrock.cube.data.copy.intercube

### ISSUE THREAD

**Issue by yyzz1010** [cubewise-code/bedrock#192]
**Describe what you did so far.**
I don't understand why pZeroSource can only be activated when pThreadMode is not 0, however it is stated that pThreadMode is an internal parameter and do not use, so pZeroSource actually is not allowed to use?

**Describe what's not working the way you expect.**
1. set pZeroSource as 1
2. source cube (pFilter used) is not clear
3. find out pZeroSource can only be activated when pThreadMode is not 0
4. however pThreadMode is an internal parameter and stated as not to use it, and pThreadMode default value is 0, so pZeroSource is not working

**Version**
- OS: Microsoft Windows Server 2012 R2 Standard
- TM1 Server Version: 11.0.204.1032

**Comment by lotsaram** [comment]
Yes I agree the check

If( pThreadMode <> 0 );

Before applying the zero out should not be there.
