### ISSUE TITLE
}bedrock.cube.data.copy.intercube

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/bedrock#20]
Hello,

I have 6 remarks on this process.

- There is a typo 'dimensons' in the documentation.
- Can we add to the documentation section in the Prolog tab how many dimensions in the cube(s) this process can handle ? Max. 27 ?
- I see in the code: 'ASCIIOUTPUT( '..\TgtFilter.txt', sTargetFilter );' Is this intended or leftover from testing ?
- I read in the documentation: "If using the pFilterParallel parameter the **single dimension** used as the "parallelization slicer" cannot appear in the pFilter parameters." This means that if I want to copy Jan, Feb, Mar, Apr data usign parallelization, and I use the month dimension as the 'pFilterParallel', all months will be looped upon 1 at a time ? Also for example December ? Or is the TI smart enough to only have 4 instances of a RunProcess call (1 for each of the 4 months in the Filter parameter) ?
- The first exercise that I wanted to tackle with this process, involves copying data on 4 measures. As my measures dimensions are always named uniquey per cube, I need to use the 'pMappingToNewDims' parameter, right ? This means 4 different calls to this Bedrock process ? Not sure this is going to be very useful in the end. For 20 measures (out of 30 in the dimension for example) this is an issue I think.
- an extension: could we make use of (public) subset names in the different filters ? That will increase the usefullness of the process a lot. The logic would be: if a subset exists with that name, use it. If not, test if the name exists as an element in the dimension. If yes, use it. If not, error message. For example, I need to copy daily data. Both source and target cube share the dimension. Days roll up in months, months roll up in years. I want to copy the daily data for only 2019-Jan, 2019-Feb, 2019-Mar, 2019-Apr. How can I do this without the use of subsets, without 'children of' kind of selections - avoiding hardcoding 120 daily elements.

**Comment by lotsaram** [comment]
Hi @wimgielis here are many questions in one. First for the easy things!
Documentation typo, fixed. Note that max 27 dimensions, done.  Removed leftover AsciiOutput from debugging.

**Parallelization**
The way the parallelization is implemented the dimension to "slice" or "chunk" on should be excluded from the filter. This is to ensure no collisions in slices which could cause overwriting conflicts. So to run on multiple threads just include the slices to use in _pFilterParallel_ only.

**Asymmetric dimension mapping**
Yes in the case you want to copy multiple different measures and the measure dimension is different then this will require one call per measure. But to call the process 4x is not such a big deal IMO. The process already copes with non-matching dimensions and can do quite a lot for a user comfortable to define the mappings but without writing any code. A useful enhancement might be to implement a "matching dimension" type logic where this need is avoided. But it isn't implemented for now (unless you want to do it). 

**bedrock conventions**
You didn't ask but worth saying in relation to your question about needing to define long filter lists. Generally this isn't necessary as by convention in bedrock if a **consolidated element** is passed in a filter and the _pSuppressConsol_ parameter is set to 1 then the consolidation will be automatically converted to a subset of all its leaf descendants when creating the view. Only if _pSuppressConsol_=0 will the conslidation be set explicitly.
Also to note if  _pSuppressConsol_=0 then for all dimension not explicitly set in the filter a subset of all leaf elements will be created and set in the view. This aids in processing speed and avoids processing unwanted intersections. (not done for leaf only views as the suppression is automatic).

**Supporting subsets in filters**
Personally I think this would be a good enhancement and I'm all in favour. The main issue is backwards compatibility and not breaking working systems. As TM1 allows name conflict between subsets and elements this would need to be tested for and elements would need to have precedence. (But with not to above of how bedrock handles consolidations in filters maybe your need is not so great if you can use consolidations?)
