### ISSUE TITLE
}bedrock.cube.data.import - double character delimiters causes error when pMappingToNewDims used

### ISSUE THREAD

**Issue by houghton-alex** [cubewise-code/bedrock#203]
**Describe the bug**
Using double character delimiters (i.e. &&) and using pMappingToNewDims parameter causes an error 

**To Reproduce**
Steps to reproduce the behaviour:
1. Execute }bedrock.cube.data.import
2. Using pMappingToNewDims parameter and delimiters as &&, ++ and ¦¦
3. Result is minor error, target dimension could not be found

**Additional Information**
Bud appears to be in Prolog in Mapping Target Dimensions region when determining the dimension and element values in the pMappingToNewDims parameter
When using single character delimiters, process runs as expected

![image](https://user-images.githubusercontent.com/50260733/92085782-a4324e80-ee0c-11ea-85c0-8417255d1f8d.png)
![image](https://user-images.githubusercontent.com/50260733/92086090-0be89980-ee0d-11ea-9c79-b354da80a33a.png)

**Comment by lotsaram** [comment]
Hi @houghton-alex 
I can see from your example screenshot that in pMappingToNewDims a **_single broken pipe character_** has been used but pEleStartDelim has been defined as double broken pipe. Therefore the process is treating the whole string passed in pMappingToNewDims as a dimension name (as no delimiter is found). So my assumption is that this is parameter input error. Please confirm.

Note _in general_ although some people do prefer to use double delimiters becasue they are "safer" this isn't really officially supported by the library (although it should work). I woudl argue it s better practice to use single characters as delimiters and just make sure that the characters used as delimiters don't occur in dimension, hierarchy or element names.

**Comment by houghton-alex** [comment]
Hi @cubewise-code/bedrock<mailto:bedrock@noreply.github.com>

Thank you for the quick reply.  Sorry, I didn’t update my code to take the screenshot after reverting to a single character. The correct screenshot is below. I ran it again with double delimiters and confirmed the error.

For now, as you suggest, I will use a single character but change to something that isn’t used in dimension, hierarchy or element names.

Cheers,
Alex

[cid:image003.png@01D68225.5ADE7EA0]

Regards,

Alex Houghton
Senior Consultant

[cid:image004.png@01D68226.0FFC9D30]

Melbourne  |  Sydney  |  Brisbane  |  Perth  |  Singapore
_______________________________
P 1300 785 336     M +61 438 471 868
E alex.houghton@qmetrix.com.au<mailto:alex.houghton@qmetrix.com.au>     W https://www.qmetrix.com.au<https://www.qmetrix.com.au/>

This e-mail (and any attachments) is confidential and intended to be accessed only by the person or entity to which it is addressed. No use, copying, disclosure or forwarding of this message or any attachments is permitted without authorisation. If you are not the intended recipient, please notify the sender immediately and delete or destroy all copies of this message and any attachments. The writer does not accept liability in connection with computer viruses or any other defects or consequences that may arise from opening or using the message and any attachments.

**Comment by lotsaram** [comment]
Hi @houghton-alex 
Do you want to have a go at drafting a fix so that the mapping to new element can handle double-digit delimiters?

**Comment by houghton-alex** [comment]
Hi Lotsaram,

Sorry for the delay in my reply. If you are able to draft a fix, I can test and validate.

Thanks,
Alex

**Comment by MateuszOszer** [comment]
Couldn't replicate. 

Exported elements that had all sort of signs in them and then inported them back, with " as pQuote and zero issues were found.

**Comment by lotsaram** [comment]
Hi @MateuszOszer before closing the issue I just want to check that you are actually testing the right thing.  
The issue which was reported specifically on this ticket was that if **double characters** are defined as the delimiters (e.g. pDimDelim=&& pEleStartDelim=¦¦ pEleDelim=++) **and** the parameter pMappingToNewDims is used that double character delimiters aren't parsed correctly when mapping into a default target element in the new dimension which wasn't present in the cube from where the export was made from. (e.g. pMappingToNewDims=NewDim¦¦PlaceholderElement)

**Comment by lotsaram** [comment]
Fixed in #243
