### ISSUE TITLE
}bedrock.cube.data.export & import: error when there is comma sign in element name

### ISSUE THREAD

**Issue by yyzz1010** [cubewise-code/bedrock#209]
**Describe the bug**
when there is comma sign in element name, the name is split into two in csv file when using bedrock export, and causing error when using }bedrock.cube.data.import

**To Reproduce**
1. use }bedrock.cube.data.export to export data (used pDelim to set a character other than comma already)
2. use }bedrock.cube.data.import to import csv file
3. as csv file split in comma automatically, element name is split into two and causing error

**Expected behavior**
even there is comma sign in element name, csv file can be used to import data via bedrock import

**Screenshots**
![image](https://user-images.githubusercontent.com/45536868/95062804-09d96980-0730-11eb-86ac-6ee8770d2ebd.png)
csv file using bedrock export

![image](https://user-images.githubusercontent.com/45536868/95062500-a2bbb500-072f-11eb-8ff8-f981e0be35ce.png)
error when using bedrock import

**Version**
* TM1 Version: 11.0.204.1032
* Operating System: Microsoft Windows Server 2012 R2 Standard

**Comment by lotsaram** [comment]
Can you please pust some more effort into a reproducible test case please?

**Comment by yyzz1010** [comment]
sorry that I found out the problem was not comma sign, it was because there is quote sign in element name, so the element name is split into two with the comma sign
![image](https://user-images.githubusercontent.com/45536868/95446064-61770f80-0992-11eb-805f-612205a72c72.png)

**Comment by MateuszOszer** [comment]
Fixed with 212
