### ISSUE TITLE
bedrock.cube.data.copy pFile Parameter Not Working?

### ISSUE THREAD

**Issue by raeldor** [cubewise-code/bedrock#211]
We have a 'vendor revenue' which is an input field and a 'final revenue revenue' which is calculated from a 'split' field.  We also have a 'parent vendor revenue' which is the parent level of 'vendor revenue' in a segment type dimension.  We are trying to cpoy from 'final vendor revenue' to 'vendor revenue', but because 'final vendor revenue' is dependent on 'vendor revenue' via the 'parent vendor revenue' we realize that doing this dynamically could have implications.  We copied the 'final vendor revenue' to a temporary measure and then copied that temporary measure to 'vendor revenue' (ie a 2-stage copy).  This worked fine.  Then we realized there was a 'pFile' parameter which copied it out to a file, which seemed like it should achieve the same result with only one call since it pushes the data out to a temp file first so it's no longer being influenced by the calcs.  Unfortunately it did not work.  So the question is... is this pFile parameter actually doing anything, and if so, why did it not work as expected?  Thanks.

**Comment by lotsaram** [comment]
Hi @raeldor  
Using pFile to transfer data internally within a cube is working for me so you need to provide some more details or a reproducible test case otherwise we can't help with your issue.
