### ISSUE TITLE
}bedrock.cube.data.export - Issue with decimal separator

### ISSUE THREAD

**Issue by macmaj** [cubewise-code/bedrock#212]
**Describe what you did so far.**
I have recently updated a snapshot process at a clients from v3 to v4.
This process used bedrock export and bedrock import to transfer data between active and snapshot version.

This has caused problems for users whos language settings in browser (they execute TI from PAW) set decimal separator as comma instead of dot.

Problem is caused by the fact that now bedrock export 'respects' those language settings and exports values with comma as decimal separator, but then incorrectly loads them because bedrock import expects dot as decimal separator.

This is caused by below lines in export:
 
![image](https://user-images.githubusercontent.com/42434036/96425956-e36e0080-11fc-11eb-82be-c56b63c8376c.png)

This part was missing from v3 and I wonder if that was done on purpose to retain users value formatting.

PS I thought that this can be manipulated with pCharacterSet but SetOutputCharacterSet doesn't have any impact on decimal separator.

PS2 I already have an alternative ways to achieve same results correctly so this question is not to get my issue at a clients resolved.

PS3 I did not test but I expect that I could experience same issues while using bedrock copy with pFile = 1

**Describe what's not working the way you expect.**

[Described above]

**Version**
- OS: Windows Server 2016
- TM1 Server Version: tested on 11.8.00000.33 and 11.6.00000.14

**Additional context**

N/A

**Comment by lotsaram** [comment]
duplicated in #232

**Comment by OliverS-Dev** [comment]
Hello,

is there a hotfix available? Or an est Release with a fix for this Bug?

Thank you!

**Comment by lotsaram** [comment]
Hi @OliverS-Dev 
No this is not addressed as yet. But if you would like to do a fix and submit a pull request then you are most welcome.

**Comment by MateuszOszer** [comment]
Fixed in main branch

**Comment by lotsaram** [comment]
@MateuszOszer can you please double-check and coordinate with @macmaj ?
From my reading of the ticket the fix is not required in the data.export process but the data.import processas this only accepty values using "." as the decimal separator and not ",".

**Comment by lotsaram** [comment]
Fixed in #244
Replace Numbr function which always uses "." as decimal separator with StringToNumber which respects local number settings.
