### ISSUE TITLE
}bedrock.cube.data.copy - pFilterParallel @<> '' and custom delimiters longer than 1 character

### ISSUE THREAD

**Issue by macmaj** [cubewise-code/bedrock#213]
**Describe the bug**
While using pFilterParallel > 1 and custom delimiters ( pEleStartDelim and pEleDelim ) longer than 1 character process errors out.
This is caused by at least those two parts in code:

![image](https://user-images.githubusercontent.com/42434036/96427397-cc301280-11fe-11eb-948a-a8e1b4d0d787.png)

It should be Long( pEleStartDelim ) and Long( pEleDelim ) instead of 1.
I did not review whole TI, but maybe this happens also with different run settings of bedrock copy process.

**To Reproduce**
As described in first sentence of description.

**Expected behavior**
Bedrock copy respects delimiters longer than 1 character

**Screenshots**

N/A

**Version**
 - OS: Windows Server 2016
  - TM1 Server Version: 11.6.00000.14

**Additional context**
N/A

**Comment by lotsaram** [comment]
@macmaj would you like to compile a fix and create a pull request?

**Comment by macmaj** [comment]
Hi @lotsaram 
I can do that.

**Comment by macmaj** [comment]
https://github.com/cubewise-code/bedrock/pull/214
