### ISSUE TITLE
}bedrock.cube.data.copy new parameter pSuppressZero

### ISSUE THREAD

**Issue by tomasfelcman** [cubewise-code/bedrock#218]
**Is your feature request related to a problem? Please describe.**
The process does not allow to copy unfed rule-calculated values from the source view.
E.g. I'm always frustrated when [...]

**Describe the solution you'd like**
I suggest creating new parameter **pSuppressZero** (as in }bedrock.cube.view.create process) that would use view zero suppression based on the parameter (default value = 1). So far there is hard coded pSuppressZero = 1 in  call of }bedrock.cube.view.create process.

**Describe alternatives you've considered**

**Additional context**
I can create pull request if you allow (I have adjusted the v2 bedrocks for this).

**Comment by lotsaram** [comment]
pull #219
