### ISSUE TITLE
}bedrock.cube.rule.manage.pro

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/bedrock#22]
A question. What is the idea behind:

##Create Blank Rule file in the data directory
IF(FileExists( cBlankRuleName ) = 0 );

  sFile = '.\' | cBlankRuleName;
  
  sCommand = 'cmd /c "(echo SKIPCHECK;) > ' | sFile | '"';
  ExecuteCommand ( sCommand, 0 );
  
  sCommand = 'cmd /c "(echo FEEDERS;) >> ' | sFile | '"';
  ExecuteCommand ( sCommand, 0 );
  
ENDIF;

Couldn't it be 2 lines of AsciiOutput instead ?

**Comment by lotsaram** [comment]
For sure this could just as well be 2 lines of AsciiOutput.

Looking at the process I'm guessing it has been done with command line vis-a-vis AsciiOutput as the later would have left a lock on the file until the prolog had closed which would mean the RuleLoadFromFile could only be done on the epilog and not all in the same place on the prolog.

**Comment by wimgielis** [comment]
Thanks a lot, makes sense
