### ISSUE TITLE
Process to create a view that uses alternate hierarchies (not default one)

### ISSUE THREAD

**Issue by reddibhatini** [cubewise-code/bedrock#222]
Hello Bedrock heros,

Is there a way  to create a view that has alternate hierarchy similar to how }bedrock.cube.view.create process creating a view(with default hierarchy) that uses pFilter as parameter?

Thanks
Abhilash

**Comment by lotsaram** [comment]
Hi @reddibhatini,

bedrock.cube.view.create creates "traditional" views which can't see or access alternate hierarchies. The only way to create views using alternate hierarchies with TurboIntegrator is via the ViewCreateByMDX function which the bedrock.cube.ciew.create.bymdx process uses.

There's no way currently in the bedrock library to create a view with MDX from a pFilter string. You could raise an enhancement request for this or you could write the code for this yourself and create a pull request to add it to the library.
