### ISSUE TITLE
}bedrock.hier.sub.delete cannot use pSub with wildcard in pMode = 2

### ISSUE THREAD

**Issue by cw-cleung** [cubewise-code/bedrock#223]
**Describe what you did so far.**
As some subsets maybe used in a cube view, hence going to delete all elements instead of destroy subset. 
Trying to achieve it by running pSub with wildcard in mode 2. 

pLogOutput  |  0
pStrictErrorHandling  |  0
pDim  |  ItemSize
pHier  |  
pSub  |  }Request_WIP*
pDelim  |  &
pMode  |  2

**Describe what's not working the way you expect.**
Got below error. 
Error: Prolog procedure line (327): Subset "}Request_WIP*" not found in dimension "ItemSize"
Seems it's plugging the pSub string with * in HierarchySubsetDeleteAllElements in Prolog 327.  
HierarchySubsetDeleteAllElements( pDim, pHier, pSub );

**Additional context**
Saw the comment and understand calling the HierarchySubsetDeleteAllElements recursively may cause performance issue. 
In fact I want to destroy all subsets, just some subsets are in used in cube view hence it throw error. 
**Can we enhance the mode 1 and check if that subset is in used in a cube view, do mode 2 instead?** 
As now running both mode 1 & 2 gives error. 

Thanks, 
Chelsea

**Comment by lotsaram** [comment]
Hi @cw-cleung 
There's no way to test in TI if a subset is used by a view. The only thing that you could do is a while loop calling hier.sub.delete with pMode=1 and if the process return code is not ProcessExitNormal then call hier.sub.delete again with pMode=2. 

Closing this issue.
