### ISSUE TITLE
Trying to Use Cube.Dimension.Delete and Getting Error File Not Found for Rule

### ISSUE THREAD

**Issue by raeldor** [cubewise-code/bedrock#224]
Trying to execute a dimension delete with preserve data and pIncludeRules=2 and get the error...

bedrock.cube.rule.manage.log
The system cannot find the file specified.

Does anyone know what causes this?  There's definitely a rule file on this cube.
Ray

**Comment by raeldor** [comment]
It looks like it's using relative paths for the file copy, but I'm guessing the working directory is not the data directory for the relevant cube. :(

**Comment by MateuszOszer** [comment]
Please check CFG file of the instance and make sure You have proper slash in the config:

LoggingDirectory=..\Log 

I've manged to replicate it by changeing the config into LoggingDirectory=../Log

Then the scan for GetProcessErrorFileDirectory Returns / and so bedrock "thinks" this is linux.
