### ISSUE TITLE
Bedrock.Dim.AllElements.Delete

### ISSUE THREAD

**Issue by jbeanz23** [cubewise-code/bedrock#23]
I passed in dim name, pEle is hardcoded to '*', pDelim is hardcoded to blank.  It calls }bedrock.hier.element.delete.  No elements were deleted from my dimension but it said process successful.  I tried running the hidden process, passing in my dimension name, i tried both '*' and blank for pEle (to delete all elements), left pHier blank and delimiter set to '&'.  Both time it says process completed successfully but no elements are deleted from my dimension.

**Comment by lotsaram** [comment]
Hi @jbeanz23 
Have checked this process and this is what I see
```
EXECUTEPROCESS('}bedrock.hier.element.delete',
    'pLogOutput', pDebug,
    'pDim', pDimension,
    'pHier', '',
    'pEle', '*',
   'pDelim', ''
);
```
_pEle_ is correctly hardcoded to \* which the B4 process interprets as "ALL"
_pHier_ is blank which is 100% OK as this is interpreted by the B4 process as "same named hierarchy"
_pDelim_ is blank **which should have been OK** but the test in the B4 process was overly restrictive

Basically this was a twin to the issue in AllConsols.Delete which you found earlier

**Comment by jbeanz23** [comment]
Sorry, that may have been a typo, i do see '*' but there is a bug in the B4, right?  It's not deleting anything no matter what i pass in.

**Comment by lotsaram** [comment]
Not sure how that one slipped through testing. It was working fine for alternate hierarchies but looking for a hierarchy called "dim:dim" in the case of same named hierarchy but of course for the same named hierarchy it's just "dim". Anyway it's fixed now.
