### ISSUE TITLE
}bedrock. cube.data.import

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/bedrock#231]
What is the purpose of the parameters pDim, pSrcEle, pTgtEle when importing data from a text file ?

**Comment by lotsaram** [comment]
This is for "remapping" data. The use case for example to copy data from one element to another. The parameters identify the dimension and source/target elements.

The functionality is limited to simpel use cases as the remapping is limited to single dimension and single element pair.

**Comment by wimgielis** [comment]
Indeed, rather limited utility I would say.

Op di 15 dec. 2020 om 17:40 schreef lotsaram <notifications@github.com>:
