### ISSUE TITLE
Bedrock.Dim.Clone

### ISSUE THREAD

**Issue by jbeanz23** [cubewise-code/bedrock#24]
When running this process i get an error that the wrong type of parameter is passed in for pHier.  It is hardcoded to a '1' and is expecting a string.  Also, should be blank or star i think?  Not sure what the 1 is.

![dimclone error](https://user-images.githubusercontent.com/8358847/56677511-8a5bf580-6675-11e9-8b8c-728c053f514e.png)

**Comment by lotsaram** [comment]
looks like this was a hangover from earlier version when pHier for the b4 process was true/false whether to include alternate hierarchies. The B3 shell wasn't updated when the B4 process was. Pull the latest version where this is fixed.
