### ISSUE TITLE
Security on Hierarchy Create from Attribute

### ISSUE THREAD

**Issue by ianboltz** [cubewise-code/bedrock#256]
When creating a hierarchy from 2.0.9.5 onwards TM1 security will need to be set for the new hierarchy created - independent of the 'master' dimension. 

I useful enhancement would be an additional parameter to copy dimension security over from the master.

**Comment by lotsaram** [comment]
@ianboltz I don't think this belongs in bedrock. The requirement is too custom and any decision to apply element security is too arbitrary. By definition the process is creating NEW elements that don't exist in the same named hierarchy. So there is nowhere to copy security from, and if setting security then to which groups
