### ISSUE TITLE
fixed backslash path separator causes compatibility issues running bedrock on Linux OS

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/bedrock#257]
**Describe the bug**
Some processes use "\" as a fixed path separator rather than testing whether the OS is Unix based vs Windows. Affected processes are:  
* cube.data.import
* cube.data.export
* hier.import
* hier.export
* hier.sub.export
* dim.attr.import  

**Expected behavior**
Processes should test the variable _GetProcessErrorFileDirectory_ to determine whether OS is Windows vs. Linux an therefore which path separator to use.  

**Additional context**
Method of how to test for OS is alreaqdy found in server.dir.backup process. Just copy this snippet and apply to all processes in library where needed.

**Comment by lotsaram** [comment]
@ianboltz if you find any more processses just add in comment to this issue.

**Comment by ianboltz** [comment]
@lotsaram I think that's it, at least on a search for / as a path separator in the .pro files
