### ISSUE TITLE
Adding the process call in the Prolog tab

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/bedrock#26]
Hello,

What I find very helpful in my own technical / generic processes, is the ExecuteProcess call to that particular process, complete with all parameters and some typical default values. For instance, I add this in the Prolog tab of my process 'TECH_unwind dimension'. Hence, calling this process somewhere else can be done with a copy/paste from there:

```
If( 1 = 0 );
## call this custom process as, for instance:
ExecuteProcess( 'TECH_unwind dimension'
  , 'pDim', 'DIMENSION NAME'
  , 'pBelowConsolidation', 'CONSOLIDATED ELEMENT'
  , 'pDeleteConsolidations', 0
  , 'pOnlyDirectChildren', 0
);
## end of process call
EndIf;
```

**Describe the solution you'd like**
Would it be an idea to do this too for Bedrock processes ? I know that there processes can be called through other user interfaces and at the time of writing processes, the calls are often automated. However, people that use Bedrock without those UI's will need to do it manually. In that case I think that this feature can add value.

In fact, for my personal TI's, I have routines in place to filter out those custom calls in the Prolog tab such that I can also call processes in an automated way (selecting them from a menu and call with arguments is injected at run-time in the TI editor). It would be good it exists for Bedrock too. Some of my processes contain 15-20 parameters hence the need to find an easy solution here.

**Comment by lotsaram** [comment]
Hi @wimgielis 
I'm not sure what to make of the question.
To me this is the sort of logic that would be embedded in a _**custom process**_ that is using bedrock for basic functions (like unwind, delete all C elements, etc.) and not embedded in a bedrock process per se.

e.g. do a test for dimension size, if >= some arbitrary number, say 500K, then call }bedrock.hier.consol.delete (passing "\*" as pConsol) else call }bedrock.hier.unwind

The bedrock processes might of course be called manually when prototyping but most of the time you would expect them to be called from a custom process with some logic embedded around them whihc is up to the developer ...

**Comment by wimgielis** [comment]
Hello lotsaram,

Not sure if we are understanding each other. What I wanted to say is that any call to a bedrock process (the mother process, not any dependent processes that are called later on by the mother process) should be added by a developer in his own TI process. Therefore, that call (ExecuteProcess, RunProcess, ...) should be scripted. If we can help that scripting by putting the call in the Prolog tab of the called process, the developer can easily copy/paste the call with default parameter values from there. It saves time and leads to less errors. Ultimately it's just for easy copy/pasting in the absence of a tool or UI that can generate that call to the mother process. The Unwind was just an example, any process is needed. It's then up to the developer to change those default values in his call to the mother process, or accept the parameter values that he copied from the Prolog tab. Does this make sense ? I use it all the time.

**Comment by lotsaram** [comment]
Hi @wimgielis 

So do you mean something like the auto-insert of bedrock 3 processes in [TI Helper](https://github.com/cubewise-code/ti-helper) (Auto Hot Key extension). Or if you are using [Arc](https://code.cubewise.com/arc-overview) (which anyone can use) then ctrl+space can be used to inteli-sense/auto-complete the ExecuteProcess complete with parameters for any process on the system.

Doesn't that meet the need you are talking about (in a more convenient way?) Otherwise I think I really have no idea what you mean.

**Comment by wimgielis** [comment]
Hello, yes it's exactly that but it would be for developers not using these tools. Would it be an enhancement ?

**Comment by lotsaram** [comment]
Hi @wimgielis 
So at it's most basic you are talking about adding somewhere in the process header an example of a call to the process?
I guess that's kinda an enhancement. But one that I think is much better served by using inteli-sense to automatically insert the snippet.

**Comment by wimgielis** [comment]
I agree about the intellisense and inserting a snippet, but that should also come from somewhere. Could we have the best of both worlds by sourcing the snippets from the Prolog section where the call, with default parameter values, is shown ? It's exactly what I do with Auto hot key ;-) and I also scan the Prolog tab of TI processes. When I don't have the AHK available, I can copy/paste from that section manually.

**Comment by lotsaram** [comment]
@wimgielis I'm going to close this issue and open a new enhancement request where it will be spelled out exactly what is meant to save confusion.

**Comment by wimgielis** [comment]
That's very good, thanks. If I can be of assistance, please let me know.


------

Best regards / Beste groeten,

Wim Gielis
MS Excel MVP 2011-2014
http://www.wimgielis.com <http://www.wimgielis.be>


Op do 2 mei 2019 om 09:29 schreef lotsaram <notifications@github.com>:
