### ISSUE TITLE
}bedrock.hier.sub.create.consolidation.leaf

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/bedrock#262]
**Describe what you did so far.**
pSubset = 'Wim';

SubsetDestroy( 'LAR_Artikel', pSubset );

ExecuteProcess( '}bedrock.hier.sub.create.consolidation.leaf', 'pLogOutput', 1, 'pStrictErrorHandling', 0,
'pDim', 'LAR_Artikel', 'pHier', '', 'pSub', pSubset, 'pConsol', '16',
'pAddToSubset', 1, 'pExclusions', '160000*',
'pDelim', '&', 'pAlias', '', 'pTemp', 1 );

AsciiOutput( 'test.txt', NumberToString( subsetgetsize( 'LAR_Artikel', pSubset ) ) );

**Describe what's not working the way you expect.**
With pTemp = 1, I get in the AsciiOutput: 20
With pTemp = 0, I get in the AsciiOutput: 11

Shouldn't we expect the same result ?
![01](https://user-images.githubusercontent.com/17201709/117731694-dc392f00-b1ee-11eb-8e42-e2fb4069778b.PNG)

**Version**
- TM1 2.0.8

**Comment by lotsaram** [comment]
We should absolutely get the same result. The only difference is that the subset will be a temporary object not registered subset but behaviour od the subset should be the same. If not then there must be a bug to do with temporary objects.  
Are you able to create a reproducible test case for IBM support?

**Comment by wimgielis** [comment]
It is reproducible in any simple dimension like a Month dimension with
elements Jan, Feb, Mar.
Let's look for the element Mar in a public subset, either temporary, either
permanent.
Result of the AsciiOutput is 1 for Permanent subsets, 0 for Temporary
subsets.

I opened a case with IBM.



# TEMPORARY SUBSET

sDim = 'Month';
sHier = 'Month';
sElement = 'Mar';
pSub = 'subset_1';


SubsetDestroy( sDim, pSub );
SubsetCreateByMDX( pSub, 'TM1SubsetAll( [ ' | sDim | ':' | sHier | ' ] )',
1 );
z = HierarchySubsetElementExists( sDim, sHier, pSub, sElement );
AsciiOutput( 'test.txt', NumberToString( z ));



# PERMANENT SUBSET

sDim = 'Month';
sHier = 'Month';
sElement = 'Mar';
pSub = 'subset_2';


SubsetDestroy( sDim, pSub );
SubsetCreateByMDX( pSub, 'TM1SubsetAll( [ ' | sDim | ':' | sHier | ' ] )',
0 );
zz = HierarchySubsetElementExists( sDim, sHier, pSub, sElement );
AsciiOutput( 'test.txt', NumberToString( zz ));






Op vr 4 jun. 2021 om 10:38 schreef lotsaram ***@***.***>:

**Comment by wimgielis** [comment]
The IBM engineer could not reproduce the error in the latest version. I
also found later on that since 2.0.9.3 (or earlier) it works so let's close
the ticket.
(Assuming that the process runs fine in the last versions - I did not test
it though since I now use a 2.0.8).

------

Best regards / Beste groeten,

Wim Gielis
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op za 5 jun. 2021 om 02:22 schreef Wim Gielis ***@***.***>:
