### ISSUE TITLE
Delimiter issue on some TIs

### ISSUE THREAD

**Issue by iansdigby-TM1** [cubewise-code/bedrock#265]
**Describe the bug**
The delimiter for Filters, e.g. on }bedrock.cube.view.create
should be a colon but after download from Github this appears as a pipe with a gap in the middle.

**To Reproduce**
1. Download bedrock 4
2. unzip and install
3. Result is '...'

**Expected behavior**
Should load as colon

**Screenshots**
<img width="140" alt="GapPipe" src="https://user-images.githubusercontent.com/85228776/120468875-9dd00380-c399-11eb-84c0-d079cbab1dd0.PNG">

**Version**
 - OS: Windows 10 Pro 20H2
  - TM1 Server Version: 10.2

**Additional context**
Easily resolved by typing in the colon - but hard to spot at first.

**Comment by lotsaram** [comment]
Hi @iansdigby-TM1 
I guess you have been living under a rock? This is a deliberate change. Bedrock 4 has been designed to work with hierarchies. As TM1 internally uses the colon as a delimiter between the dimension name and hierarchy name we excluded using colon in the default delimiters to avoid ambiguity and broken pipe is used in its place.  
This is just the standard delimiter between dimension/hierarchy name and the first element. At run time you are of course free to substitute whatever delimiters you like. Just make sure that the delimiters match what is used in the filter expression.
