### ISSUE TITLE
}bedrock.cube.data.clear does not handle hierarchies

### ISSUE THREAD

**Issue by zsoltmoravcsik** [cubewise-code/bedrock#266]
When the }bedrock.cube.data.clear process called the process does not except hierarchies in any format.
Could we add the dimension:heirName as an valid parametrization when using pFilter:Dim¦Element& format?? Example pFilter:Products:Products2020¦Element&

**Comment by lotsaram** [comment]
Hi @zsoltmoravcsik  
Yes it's becasue cube.data.clear has a dependency on cube.view.create which only handles traditional views and not MDX views. As traditional views don't deal with hierarchies the only way to address a hierarchy in a view is via MDX view. Therefore alternate hierarchies are not accepted in bedrock filter parameters.  
The current workaround would be to use ViewCreateByMDX and then do ViewZeroOut.
