### ISSUE TITLE
}bedrock.cube.view.create.bymdx does not work with hierarchies

### ISSUE THREAD

**Issue by zsoltmoravcsik** [cubewise-code/bedrock#267]
**Describe the bug**
Try to clear cubes with hierarchies. Here is a code snipet from the process:
# to make sure that the name of the dim is not part of the name of another dim
        If(Scan(pDimDelim|sDimString|pEleStartDelim, sTFilter)=0 & Scan(sDimString|pEleStartDelim, sTFilter)<>1);
            sProc   = '}bedrock.hier.sub.create';
            nRet    = ExecuteProcess( sProc,
                'pLogOutput', pLogOutput,
                'pStrictErrorHandling', pStrictErrorHandling,
                'pDim', sDimC,
                **'pHier', '',**
                'pSub', sSubset,

Highlighted process call does not pass the hier variables.
Please fix the }bedrock.cube.view.create.bymdx and handle hierarchies properly.

Thanks.

**Comment by lotsaram** [comment]
You are welcome to do fix and create pull request.

**Comment by lotsaram** [comment]
Hi @zsoltmoravcsik 
I would have to have a look at this but it seems strange to me that view.createbymdx is calling hier.sub.create. Can't see a reason why this would be necessary. Can you elaborate? Becasue in the unit tests which we use views are created that are using alternate hierarchies.

**Comment by lotsaram** [comment]
Hi @zsoltmoravcsik 
I looked into this and the snippet you included is from _cube.view.create_ **not** _cube.view.create.bymdx_  
Yes cube.view.create does not work with hierarchies becasue it is for creating traditional views only and references to alternate hierarchies in the filter are rejected. Only MDX views support hierarchies, therefore to use hierarchies just call the cube.view.create.bymdx process.
