### ISSUE TITLE
}bedrock.cube.data.copy.pro with pFile = 1 has double quote issue 

### ISSUE THREAD

**Issue by cw-cleung** [cubewise-code/bedrock#269]
**Describe the bug**
}bedrock.cube.data.copy.pro with pFile = 1 (using Bedrock export & import) hardcoded to use comma as delimiter and double quote as quote, which cause errors when copying data with elements contain these two characters. 

Suggest to add parameter to let user set pQuote and pDelimiter, keep , and " as default.

**Comment by lotsaram** [comment]
Hi @cw-cleung 
The same feedback for you as many others. Don't just raise this as an issue. This is a community project. do the enhancement in your fork to add pQuote and pDelimiter parameters to the data.export and data.export processes and then raise a pull request to patch your enhancement into the project. Then everyone benefits.
