### ISSUE TITLE
Copy Calculated Cell Over Non Calculated Cell Not Working

### ISSUE THREAD

**Issue by raeldor** [cubewise-code/bedrock#271]
It seems to not be copying data where data does not exist in the destination.  My cube looks like this...

![image](https://user-images.githubusercontent.com/1768444/124922545-74188680-dfae-11eb-880e-b85c478ba217.png)

And my rules like this...

![image](https://user-images.githubusercontent.com/1768444/124922664-901c2800-dfae-11eb-95ac-363024c53893.png)

But when I do a copy using this code...

![image](https://user-images.githubusercontent.com/1768444/124922744-ab873300-dfae-11eb-81fc-ed39ecbf7992.png)

It doesn't copy the value 60000 for 21Vianet.  The destination cell is not a calculation and I have suppress rules set to zero, so surely this should copy?

**Comment by lotsaram** [comment]
Hi @raeldor  
Don't forget that like any process **ViewExtractSkipZeroesSet** which is set according to the **pSuppressZero** parameter in the bedrock processes is not really skipping null values but in the case of rule calculated leaf cells is _skipping any cells with value of zero AND any cells which are not fed regardless of their value.  
My guess is that you will find the intersection of 21Vianet | EUS is not fed. To verrify you can check feeders on this cell or limit the scop of the filter as the data source for the process to a very small slice and set pSuppressZero=0 and check the result.

**Comment by raeldor** [comment]
Thank you.  I don't see an option for pSuppressZero in the documentation, or it's relation to unfed cells.  I'll give it a try, thank you.  Is it worth updating the documentation to reflect this option?

**Comment by lotsaram** [comment]
Yes the documentation should be updated! But if you have the latest version then you can see that the parameter is there.

**Comment by raeldor** [comment]
Great, thank you.
