### ISSUE TITLE
pIncludeRules: 2 in }bedrock.cube.dimension.add

### ISSUE THREAD

**Issue by matannon** [cubewise-code/bedrock#274]
Hello,
Every time, I try to use this bedrock: }bedrock.cube.dimension.add
All is good without the rule reload.
I don't have the reload of the rule when I choice the option 2.
Is this a known bug?
I noticed this several times. So I copy my rule before starting the process.

Thanks,

**Comment by lotsaram** [comment]
Hi @matannon 
I cannot replicate this issue using the current bedrock 4. When I add a dimension to a cube with pIncludeRules=2 the new cube with extra dimension has the rules attached.
