### ISSUE TITLE
}bedrock.cube.data.import.pro with cubes bigger than 12 dimensions

### ISSUE THREAD

**Issue by Capricorn2756** [cubewise-code/bedrock#275]
**Describe the bug**
Process ends with error when importing data in cube bigger than 12 dimensions. 
Process writes in log: 
%DataSourceLine% Error: Data procedure line (686): Invalid key: Dimension Name:%DimName№13%, Element Name (key):%ElementNameFromDim№12%

**To Reproduce**
Run process with any cube bigger than 12 dimensions

**Expected behavior**
Data should be imported in cube

**Version**
 - OS: Windows Server 2106 Standard, version 1607, build 14393.4530
  - TM1 Server Version: 11.8.00100.13

**Additional context**
As I have checked code of process,  it looks like you forgot to increment variable **nSourceIndex**  after line 1132 of code.

**Comment by tomasfelcman** [comment]
Hi I have created a Pull request #276  with the fix.
