### ISSUE TITLE
 }bedrock.cube.data.copy.intercube won't work for cube with 13 dimensions

### ISSUE THREAD

**Issue by pbuncik** [cubewise-code/bedrock#28]
The process will output error when running on a cube having 13 dimensions.

**To Reproduce**
1. Run with parameters pSrcCube - any cube having 13 dimensions
3. Result is error that last dimension is missing an input element in pMappingToNewDims.

**Expected behavior**
Process should work on any cube up to 27 dimensions.

**Screenshots**
NA

**Version**
 - OS: Windows Server 2012 R2
  - TM1 Server Version: PAL 2.0.6

**Additional context**
The issue is located in prolog code - invalid variables are populated with values in cases of cube with 13 and 14 dimensions. The issue is most probably a typo.

**Comment by lotsaram** [comment]
Thanks for confirming @pbuncik 
even happier if you patch it and do a pull request. :-)

**Comment by lotsaram** [comment]
resolved by #30
