### ISSUE TITLE
how to create create a view with dimension hierarchies.  }bedrock.cube.view.create is not talking hierarchy names in pFilter

### ISSUE THREAD

**Issue by reddibhatini** [cubewise-code/bedrock#281]
Is there a way we can pass hierarchy names to process '}bedrock.cube.view.create'??
I am looking to create a view with hierarchy that is not a DEFAULT hierarchy.

**Comment by lotsaram** [comment]
No. _view.create_ constructs a "traditional view" which can only address the same named hierarchies.
To construct a view which uses alternate hierarchies the only way is via MDX. The view.create.bymdx process can do this.

**Comment by reddibhatini** [comment]
Thanks @lotsaram @RaduCantor 

How about cube data copies that are sourcing view with hierarchies??
Any simple way similar to }bedrock.cube.data.copy?
