### ISSUE TITLE
}bedrock.cube.data.import, ability to skip record for missing data points.

### ISSUE THREAD

**Issue by x-Adam-x** [cubewise-code/bedrock#284]
**Is your feature request related to a problem? Please describe.**
When moving data between instances in some cases not all elements exist in the dimensions of the cube on the target instance. I know this and accept this will result in a loss of data. Loss of data is already accepted by checking the cellisupdatable.  In the current process, where the data point does not exist for a record, an entry is added to the process log and the process completes with minor errors. I would prefer that the process skips those records that do not have a data point and complete successfully.

**Describe the solution you'd like**
An additional parameter, 'pStrict' with the default value 1. If pStrict = 1 then the current behaviour is maintained. If pStrict = 0 then the element is for the dimension is checked. If the element does not exist in any dimension the record is skipped.

**Describe alternatives you've considered**
Due the number records and different target instance the checking needs to be handled in the }bedrock process.

**Additional context**
Here is updated }bedrock.cube.data.import with new parameter pStrict. 
[}bedrock.cube.data.import.txt](https://github.com/cubewise-code/bedrock/files/7742770/bedrock.cube.data.import.txt)
 ( .pro as txt to confirm to file type restrictions.)

**Comment by lotsaram** [comment]
There is an existing parameter `pStrictErrorHandling`  
Why not use that?

**Comment by lotsaram** [comment]
Actually on 2nd thoughts using `pStrictErrorHandling` would be a bad idea as this operation needs it's own parameter as you definately don't want this option switched on by default. The reason being is that this operation would be ridiculously expensive as it would require an additional Dimix test on every variable on every record. I think to be honest that this is unlikely to get done unles you are prepared to do it.  

The production of a process error log file may be inconvienient in your particular use case but at lease you have a record of the elements in the source which don't exist in the target.

**Comment by lotsaram** [comment]
@x-Adam-x yes will add this. The default behaviour will remain as current but with option to skip.
