### ISSUE TITLE
}bedrock.dim.attr.importfromfile needs unix file structure validation added

### ISSUE THREAD

**Issue by ianboltz** [cubewise-code/bedrock#287]
**Describe the bug**
Existing code is windows based

# Validate source dir
If( FileExists( pSrcDir ) = 0 );
    nErrors = 1;
    sMessage = 'Invalid source directory specified: folder does not exist.';
    DataSourceType = 'NULL';
    LogOutput( cMsgErrorLevel, Expand( cMsgErrorContent ) );
EndIf;
If( SubSt( pSrcDir, Long( pSrcDir ), 1 ) @<> '/' );
    pSrcDir = pSrcDir | '/';
EndIf;

**Expected behaviour**
Needs 

## check operating system
If( Scan('/', GetProcessErrorFileDirectory)>0);
#  sOS = 'Linux';
  sOSDelim = '/';
Else;
#  sOS = 'Windows';
  sOSDelim = '\';
EndIf;

**Comment by lotsaram** [comment]
@ianboltz don't know what version you tested on but this is was fixed in #258 in April 2021
