### ISSUE TITLE
Process to create a view that uses alternate hierarchies

### ISSUE THREAD

**Issue by reddibhatini** [cubewise-code/bedrock#290]
Problem:
The current "bedrock.cube.view.create" creates "traditional" views which are unable to see/view  access alternate hierarchies. 
Currently there is no way in the bedrock library to create a view with MDX from a pFilter string

what I want to happen.
Update "bedrock.cube.view.create" TI process to create views from alternate hierarchies using "pFilter" as parameter.

**Comment by lotsaram** [comment]
There is already https://github.com/cubewise-code/bedrock/blob/master/main/%7Dbedrock.cube.view.create.bymdx.pro 
Alternate hierarchies require a MDX view. Bedrock views are purely for data processing and have no concept of rows, columns or filter.  
How would you propose that it should work? Should all filter elements be passed into a cross-join tuple on columns with no rows and no filter?

**Comment by reddibhatini** [comment]
Currently I am creating a view with all dimensions cross-join(leaves hierarchy) and using this in viewzeroout(and source,target version copies)

**Comment by reddibhatini** [comment]
If I give pfilter expression as
Version:Version:Actuals
The process should create a view with Actuals version cross joining with rest of all other dimensions(leaves hierarchy)

**Comment by lotsaram** [comment]
Why? To be honest I don't see the point of what you're proposing. If we leave string data asside as an exception all data in TM1 is stored at leaf intersections. If you want to clear data then alternate hierarchies aren't needed.  
You need to come up with a better use case of why you think this is needed.

**Comment by reddibhatini** [comment]
@lotsaram 
Lets say we have dimension dim1 with 2 hierarchies hier1(elements: 'A','B') and hier2(elements: 'B', 'C')
If I need to do a whole version copy, I need to include both the hierarchies(elements: A,B,C) element's data.

**Comment by lotsaram** [comment]
Hi @reddibhatini sorry to labor the point here but there's somethign fundamentally wrong with your model if not all leaf elements containing data are present in one hierarchy. If this is true you would never be able to see the true total. 

The purpose of the bedrock library is manipulating cube data via TI. If all leaves are present in the same named hierarchy then in order to do a complete vesion copy there is no requirement to use alternate hierarchies (and therefore a MDX view).
