### ISSUE TITLE
Exporting and importing values

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/bedrock#291]
My scenario is as follows. There is 1 cube with rules, for which we need to export the historical values (2014-2020), then turn off rules for these years, clear the values, and import again.

Hence, I call the cube data processes for export, clear, import.

The problem is with decimal separators.

**Describe the bug**
The export is as such:

![image](https://user-images.githubusercontent.com/17201709/154683806-be75ba82-c9ef-46c1-b52f-e56f58417301.png)

The value of 0.0001 comes in the text file as 0,0001. I can live with that.

Without changing the exported text file (there is 1 file per year), after importing the value in the cube is 1:

![image](https://user-images.githubusercontent.com/17201709/154684050-836fe20d-3611-40c6-a597-7759cdc3193c.png)

Hence, all values are way off (several powers of 10, into the billions depending on how many decimal figures we have.)

The processes use NumberToString and StringToNumber. Also . and , have been set in the data source options of the import process. Changing these 2 last values already has an impact on the imported values.

My workaround for now is Notepad++ to change the , into a . for all decimal values. This takes ages since the exported files have billions of characters (tens of millions of rows).

**To Reproduce**
I am working at the customer now but I guess it can be reproduced easily.

**Expected behavior**
I would expect to have a parameter for both settings, in the export and import processes. Then the processes would use these settings, irrespective of what is in the data source of the import process.

**Screenshots**
See above.

**Version**
 - very recent

**Comment by lotsaram** [comment]
I thought there was already an enhancement request to set the ascii delimitors on export and import but I can't find it.

**Comment by tomasfelcman** [comment]
Hi guys, there has been a Pull request by JanHrbek https://github.com/cubewise-code/bedrock/pull/264 fixing this, but it has not been committed ever since...
Please have a look at that and approve if applicable.

BR,
Tomas

**Comment by lotsaram** [comment]
Resolved in #264
