### ISSUE TITLE
Add ProcessExecute example snippet in prolog

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/bedrock#31]
**Is your feature request related to a problem? Please describe.**
In most cases a developer **should** have access to either an IDE which supports auto-complete for TI processes or a free AHK app to achieve the same result in more basic editors. However, when these options are not available a "low tech" helpful feature would be for the header of each bedrock process to contain a snippet to call the process which can simply be copy/pasted by the developer into whichever custom process they are writing.

**Describe the solution you'd like**
Insert a region immediately above the GeneratedStatements. Example below for [}bedrock.chore.execution.check](https://github.com/cubewise-code/bedrock/wiki/%7Dbedrock.chore.execution.check) for no other reason than it is alphabetically the first bedrock process.
```
#Region CallThisProcess
# A snippet of code provided as an example how to call this process should the developer be working on a system without access to an editor with auto-complete.
If( 1 = 0 );
ExecuteProcess( '}bedrock.chore.execution.check', 'pLogOutput', pLogOutput,
    'pMonthDays', '',
    'pWeekDays', '',
    'pDelim', '&',
    'pStartTime', 0,
    'pEndTime', 24
);
EndIf;
#EndRegion CallThisProcessExample
#****Begin: Generated Statements***
#****End: Generated Statements****

```
_Note:_ the snippet is provided within a non-executing IF rather than commented out for the explicit purpose of making copy/paste to a custom process as easy as possible.

**Describe alternatives you've considered**
* [Arc](https://code.cubewise.com/arc-overview)
* [TI Helper](https://github.com/cubewise-code/ti-helper)
* Custom AHK app

**Additional Information**
See #26

**Comment by wimgielis** [comment]
Good summary ! What I did not find back in the description is that those IDE's / automation tools can source the process calls from that dedicated region in the Prolog section.

I really think that the vast majority of TM1 customers / administrators in Belgium and surrounding countries, who do not use/know Cubewise stack of products, can take advantage of this feature. The places where I do TM1 consultancy don't know Cubewise, let alone its products.

**Comment by wimgielis** [comment]
Is that Region ... EndRegion generated by Planning Analytics and put manually ? Put differently, how do you edit the PRO files ? Because for processes that have a 27-dimensional cube as the source, that will be tricky. Do you edit the PRO files themselves ?

**Comment by lotsaram** [comment]
The Region -> EndRegion adds a folding section in the code such that only the first line where the Region starts is visible and the other rows are collapsed and open/close can be toggled on mouse-click. This is supported in PAW, Performance Modler, Arc, ... You need to type the Region/EndRegion manually (or via shortcut accelerator key, depending on editor).

We do actually have a library process to create a dummy cube and view from 1 -99 dimensions, but it isn't part of bedrock ( ... maybe it should be.)

But it doesn't matter as if editing in a newer editor variables are only refreshed from source on request, so if the cube or view set on the data source doesn't exist then it is of no consequence. You can still edit the "advanced" tabs and save the process and the variables stay as is. So I really recommend that you try out a new editor, it is hard to go back once you have.
