### ISSUE TITLE
CubeSetLogChanges

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/bedrock#316]
Hello,

I see the function CubeSetLogChanges in several Bedrock processes, a.o. }bedrock.cube.data.clear, }bedrock.cube.data.copy, }bedrock.cube.data.export. Wouldn't it be better to have CellPutS to the }CubeProperties cube on measure 'LOGGING' ?

**Comment by lotsaram** [comment]
> Wouldn't it be better to have CellPutS to the }CubeProperties cube on measure 'LOGGING' ?

Maybe in terms of preventing locking. However, I would assume that in most cases where bedrock is used in production whatever the calling process is should be handling the logging switches and the option passed to the bedrock process would be to ignore changing the logging switches.

For running manually there should be no difference.
