### ISSUE TITLE
}bedrock.cube.data.copy.intercube clears whole target cube despite pFilter parameter

### ISSUE THREAD

**Issue by pbuncik** [cubewise-code/bedrock#32]
**Describe the bug**
}bedrock.cube.data.copy.intercube will clear whole target cube event if the pFilter parameter is specified and filtered dimension/elements exist in both source and target cube.

**To Reproduce**
1. Go to process '}bedrock.cube.data.copy.intercube'
2. As pSrcCube, pTgtCube parameter values pick any cubes with same dimensionality and use pFilter to slice both source and target cube
3. Target cube is cleared completely despite pFilter was set.

**Expected behavior**
According to pZeroTarget documentation: OPTIONAL: Zero out Target Element PRIOR to Copy? (Boolean 1=True) Clears combination of pFilter and pMappingToNewDims

**Screenshots**
NA

**Version**
 - OS: Windows Server 2012 R2
  - TM1 Server Version: PAL 2.0.6.

**Additional context**
Variable used for clearing target cube view `sTargetFilter` is empty, variable sFilter is set to pFilter and '+' concatenated to the end of pFilter.

**Comment by lotsaram** [comment]
@pbuncik seem as we need this working for other stuff we are working on ;) I nominate you to fix it
