### ISSUE TITLE
Exported file name in lower cases on Linux when using cube copy process

### ISSUE THREAD

**Issue by macsir** [cubewise-code/bedrock#322]
**Describe the bug**
Exported file can't be found when importing using cube copy process on Linux

**Version**
 - OS: Linux

**Additional context**
All tm1 files including the temporary exported files are in lower-case file names. Especially when the cube name has upper cases, the import process can't find the proper file name. **pCube = LOWER(pCube);** can fix the bug when on Linux.

```## check operating system
If( Scan('/', GetProcessErrorFileDirectory)>0);
#  sOS = 'Linux';
  sOSDelim = '/';
  pCube = LOWER(pCube);
Else;
#  sOS = 'Windows';
  sOSDelim = '\';
EndIf;

## File location for indirect data copy
cDir    = '.' | sOSDelim;
cFileName = pCube | cTimeStamp | cRandomInt | '.csv';
cFile   = cDir | cFileName;
cTitleRows = 1;
cDelimiter = ',';
cQuote = '"';```

I can do the PR if you like. Thanks.

**Comment by lotsaram** [comment]
Hi @macsir thanks for noticing this. Yes if you would like to create a pull request with the fix you're more than welcome to :-D
