### ISSUE TITLE
}bedrock.cube.data.import - How to use pZeroFilter

### ISSUE THREAD

**Issue by macmaj** [cubewise-code/bedrock#328]
**Describe what you did so far.**
During embedding of cube.data.export and cube.data.import pair in TIs I stumbled upon pZeroFilter parameter which would be useful to me as it would allow me to streamline my main TI and remove separate run of cube clear data.

**Describe what's not working the way you expect.**
I can't find how I can embed that line with zero filter in export generated by cube data export.
I would assume that there would be a 'sister' parameter there that would allow me to choose if I want to add a zero filter or not.
Either based on the provided export filter or a separate one.

Please let me know if I'm missing something or if that feature is not complete.

**Version**
N/A

**Additional context**
N/A

**Comment by lotsaram** [comment]
Hi @macmaj  
Provided the documentation for the parameters is correct I believe you can do this using

- pTitleRecord=2 in _cube.data.export_
- pZeroFilter=2 in _cube.data.import_

> **_cube.data.export_** : **pTitleRecord**
> OPTIONAL: Include Title Record in Export File? (Boolean 0=false, 1=true, 2=title and filter line Default=1)

> **_cube.data.import_** : **pZeroFilter**
> OPTIONAL: Source file includes Zero out filter (0=No filter line in source file, 1=Ignore filter line, 2=Perform ZeroOut using filter line)

**Comment by macmaj** [comment]
Hi @lotsaram 
I have missed that pTitleRecord can equal 2 and in this case it also includes a filter line. I was looking for a separate parameter.
Thanks for letting me know.
