### ISSUE TITLE
Wrong number format in the output by }bedrock.cube.data.export

### ISSUE THREAD

**Issue by CWako** [cubewise-code/bedrock#359]
**Describe the bug**
If nValue has a comma as decimal separator, NumberToString ignores it (expecting a point as decimal separator) and "upscales" the value in the output.

Instead NumberToStringEx should be used to force the correct output with a point as decimal separator regardless of the format of nValue.

}bedrock.cube.data.export > data tab > row 25 et seq.

'### Export data from source version to file ###
If( value_is_string = 0 );
    #sValue = NumberToString( nValue );
      sValue = NumberToStringEx( nValue, '#,0.#####', '.', ',' );
EndIf;.

**Comment by lotsaram** [comment]
This was fixed in #264 in May 2022 
Your system has an outdated bedrock version. Probably best to update.
