### ISSUE TITLE
SubsetAliasSet vs HierarchySubsetAliasSet

### ISSUE THREAD

**Issue by gtonkin** [cubewise-code/bedrock#368]
Minor one but should setting the alias in }bedrock.hier.sub.create.bymdx.pro use the hierarchy function to future-proof it?:

`SubsetAliasSet( pDim | ':' | sHier, pSub, pAlias);`

vs

`HierarchySubsetAliasSet( pDim, sHier, pSub, pAlias);`

(around line 160)

**Comment by lotsaram** [comment]
Hi @gtonkin as per my understanding from a reliable source at IBM all the hierarchy functions are actually nothing more than a routing to the dimension function with the dimension name passed as the concatenation of dimension and hierarchy. So both are functionally equivalent. (Maybe v12 might be different but I very much doubt it.)

**Comment by gtonkin** [comment]
Good to know - thanks!
