### ISSUE TITLE
}bedrock.security.group.delete.pro - incorrect line count for Prolog tab

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/bedrock#376]
**Describe the bug**
The Prolog line count says 224 in the PRO file, it should be 223.

**To Reproduce**
Processes('}bedrock.security.group.delete')/tm1.Compile
gives an error on Prolog tab line 224:
Syntax error on or before: "
,4
 missing semicolon "

**Comment by lotsaram** [comment]
Thanks. I can replicate this with latest pull. It's really annoying sometimes the change sensitivity of git messes up merges. But the real issue is that the pro files aren't pure code but have other properties in there. Have fixed it.
