### ISSUE TITLE
}bedrock.dim.clone takes way to long for large dimensions 

### ISSUE THREAD

**Issue by PawanKumarRohilla** [cubewise-code/bedrock#38]
**Describe the bug**
}bedrock.dim.clone takes too long to clone large dimensions
I looked into the code and found that }bedrock.hier.unwind is the culprit  
please model it based on V3 bedrock for one hierarchy so that it becomes blazingly fast

**To Reproduce**
1. Go to process '...'
2. Run with parameters '....'
3. Result is '...'

**Expected behavior**

**Screenshots**

**Version**
 - OS: [e.g. Windows Server 2106]
  - TM1 Server Version: [e.g. 11.4]

**Additional context**

**Comment by lotsaram** [comment]
@PawanKumarRohilla I'm not sure I understand what your point is. Unwind is inherently slow for large dimensions as the code must recourse through all relationships and break all parent-child bonds. The logic for unwind I don't think is changed between v3 & v4.

However if the use case is to replace an existing dimension with a copy from another dimension. Then do you need to unwind? Why not use the mode option to delete all elements? Then it will be fast.

**Comment by PawanKumarRohilla** [comment]
@lotsram thank you for your reply.  I used pUnwind=1 to not lose any cube data should any of the elements are no longer in source dimension.
I can use pUnwind=2 but then the hierarchies will not unwind. 
If pUnwind is passed as 1 it makes the unwind process error out as it passes pConsol='' which causes error in hier unwind process

It takes long time to run for large dimsnsions as  the process is calling itself recursively which was not the case with v3.  In v3 i ran the unwind process which took around 2 seconds while v4 I had to cancel after 500 seconds.
All above issues are kinda linked  please try to replicate.

**Comment by lotsaram** [comment]
fixed by #51
