### ISSUE TITLE
Planning Analytics version 12 and bedrock

### ISSUE THREAD

**Issue by janus-t** [cubewise-code/bedrock#382]
Hi

Is there plan to create version 12 (currently available as PAaaS on AWS and Cloud Pak for Data environments) compatible version of bedrock processes?

Here's one example where deprecated TI functions will break process. Process }bedrock.cube.data.import has line with CubeSetLogChanges() function, which isn't available in version 12.
https://github.com/cubewise-code/bedrock/blob/0c334d5f6abf80b04b7c1b7ad0997ff2b01fbad6/main/%7Dbedrock.cube.data.import.pro#L2439

- Janus

**Comment by lotsaram** [comment]
Hi @janus-t 
Yes there will be a new version of bedrock for v12 which will remove all non-supported functions. There's no timeline for this project yet.
