### ISSUE TITLE
}bedrock.cube.data.copy.intercube does not apply pDimDelim with more than 1 character correctly

### ISSUE THREAD

**Issue by tomasfelcman** [cubewise-code/bedrock#386]
**Describe the bug**
When specifying pDimDelim with more than 1 character (for example &&& instead of default &) the pMappingToNewDims does not parse the filter correctly.

**To Reproduce**
1. specify dim delimiter & - works correctly
2. specify dim delimiter &&& and adjust pMappingToNewDims accordingly
3. error is logged with non-sense information about dimension "" does not exist
 such as:  TM1.TILogOutput   }bedrock.cube.data.copy.intercube : In pMappingToNewDims - an element delimiter must follow a dimension name: & (15) : Admin

**Expected behavior**
No error and correct parsing

**Screenshots**

**Version**
 - OS: Windows Server 2016
  - TM1 Server Version: 11.4

**Additional context**
There is wrong nAddExtra handling. I will create additional Pull request to fix that...

**Comment by lotsaram** [comment]
Fixed in #387
