### ISSUE TITLE
}bedrock.cube.data.copy - watcher creates semaphore files for child threads

### ISSUE THREAD

**Issue by pbuncik** [cubewise-code/bedrock#388]
**Describe the bug**
Watcher (main thread) creates semaphore files for child threads, which attempt to delete the semaphore files on their own. But since the files are created in scope of main thread commit, the child threads might be prone to locking issue.

**To Reproduce**
Running the process in parallel (pParallelThreads > 1) should reveal the issue.

**Expected behavior**
No locking should happen.

**Screenshots**
N/A

**Version**
 - OS: CentOS 7
  - TM1 Server Version: 11.8.01900.10

**Additional context**
N/A

**Comment by lotsaram** [comment]
#389 was intended to address this issue but had to be rejected due to diff conflict
