### ISSUE TITLE
Sandbox and TI

### ISSUE THREAD

**Issue by jkp713** [cubewise-code/bedrock#391]
**Is your feature request related to a problem? Please describe.**
While using sandboxes in TI, I’ve encountered a situation. Data source is cube view, and the view is created with }bedrock.cube.view.create.

After I set the sandbox with:

ServerActiveSandboxSet(pSandbox);
SetUseActiveSandboxProperty(1);

bedrock creates the view, but TI takes the source values from the base view, even after setting sandbox in the prolog,

But this is not a situation for all cases, I’ve tested in a different instance, and there was no such case and setting the sandbox in the prolog was enough for }bedrock.cube.view.create,

**Describe the solution you'd like**
Adding a sandbox parameter to }bedrock.cube.view.create,

**Additional context**
To overcome this, I added a sandbox parameter to }bedrock.cube.view.create, this it seems fine and working, I also created a pull request for this you can inspect

**Comment by lotsaram** [comment]
Fixed by #390
