### ISSUE TITLE
Cube rule gets deleted after removing a dimension from a cube

### ISSUE THREAD

**Issue by JLKunze** [cubewise-code/bedrock#407]
**Describe the bug**
When using the process '}bedrock.cube.dimension.delete' and setting the parameter 'pIncludeRules' to 1, the cube-rule gets deleted. In the logs it says that the rule was unloaded successfully, yet it can't be found anywhere.

**To Reproduce**
1. Go to process '}bedrock.cube.dimension.delete'
2. Run with parameters 'pIncludeRules' = 1
3. Result is that the rule goes missing

**Expected behavior**
I expected the rule to be unloaded in the data-folder like the wiki said.

**Screenshots**

**Version**
 - OS: [e.g. Windows Server 2019 Standard]
  - TM1 Server Version: [e.g. 11.8]

**Additional context**

**Comment by lotsaram** [comment]
Hi @JLKunze 
So was there an error in the parameters given and the process works as expected?

**Comment by JLKunze** [comment]
Hi @lotsaram 
I sadly have to admit that the problem lies with me. The process and the parameters work just as they should. I searched for the .rux-file after the process finished only to find out that the file gets saved as a .txt-file... 
To sum up, I was wrong :)
