### ISSUE TITLE
}bedrock.cube.view.publish error on pClient

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/bedrock#43]
**Describe the bug**
Process }bedrock.cube.view.publish returns error because of error in Epilog: pClient is not a parameter used in this process.

Else;
    sProcessAction = Expand( 'Process:%cThisProcName% successfully published view %pView% in cube %pCube% **created by cient %pClient%**.' );

**To Reproduce**
1. Go to process '}bedrock.cube.view.publish'
2. Run with parameters 'Existing Cube/View & rest is defaults'
3. Result is 'Error: Epilog procedure line (16): Variable "pClient" not found'

**Expected behavior**
No errors on successful execution

**Screenshots**
NA
**Version**
 - OS: Windows Server 2012 R2
  - TM1 Server Version: PAL 2.0.7 (11.5.00000.23)

**Additional context**
NA

**Comment by lotsaram** [comment]
fixed in #45
