### ISSUE TITLE
}Bedrock.Hier.Element.Create

### ISSUE THREAD

**Issue by jbeanz23** [cubewise-code/bedrock#47]
**Describe the bug**
No element is added when trying to add an N level element to a dimension.  It says process completed but nothing is added

**To Reproduce**
1. }bedrock.hier.element.create or Bedrock.Dim.Element.Create
2. Run with parameters (pDim= Currency, pHier =i tried blank and *, pEle = USD, pEleType = N, pInsertionPoint = blank, pDelim = &
3. Result is process completed successfully but no element is added

**Expected behavior**
A new element USD is available in currency dimension

**Screenshots**

**Version**
 - OS:  Windows Server 2016 standard
  - TM1 Server Version: 11.4

**Additional context**

**Comment by lotsaram** [comment]
This is the problem. It's nothing to do with element type but that the hierarchy isn't handled properly for the _**same named hierarchy**_ which is resolved as dim:dim _**not**_ dim.
![image](https://user-images.githubusercontent.com/29408388/57766389-92083a80-7707-11e9-9ffd-f11865c01467.png)

**Comment by lotsaram** [comment]
fixed in #48
