### ISSUE TITLE
}bedrock.cube.data.copy question

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/bedrock#50]
**Describe what you did so far.**
It's probably something very stupid, but I just don't see what I'm doing wrong here:

Cube: kh_sg with Dim:
  kh_verf
  kh_jahr
  kh_perio
  kh_versi
  kh_waehr
  kh_kons
  kh_konz
  kh_ges
  kh_segme
  kh_bgkto
  
ExecuteProcess('}bedrock.cube.data.copy',
	'pLogOutput',1,
	'pCube','kh_sg',
	'pSrcView','',
	'pTgtView','',
	'pFilter','',
	'pFilterParallel','',
	'pParallelThreads',2,
	'pEleMapping','kh_versi:V01->RY2019_4QOB_F',
	'pMappingDelim','->',
	'pDimDelim','&',
	'pEleStartDelim','¦',
	'pEleDelim','+',
	'pFactor',1,
	'pSuppressRules',1,
	'pCumulate',0,
	'pZeroTarget',1,
	'pZeroSource',0,
	'pTemp',1,
	'pCubeLogging',0,
	'pThreadMode',0);
	
7456   [1]   ERROR   2019-05-21 15:35:57.611   TM1.TILogOutput   Process:}bedrock.cube.data.copy ErrorMsg:An element start delimiter must follow a dimension name: -> (13)
7456   [1]   ERROR   2019-05-21 15:35:57.611   TM1.TILogOutput   Process:}bedrock.cube.data.copy ErrorMsg:Element: kh_versi:V01 does not exist in dimension kh_bgkto
7456   [1]   ERROR   2019-05-21 15:35:57.611   TM1.TILogOutput   Process:}bedrock.cube.data.copy ErrorMsg:the process incurred at least 1 error. Please see above lines in this file for more details.
7456   [1]   ERROR   2019-05-21 15:35:57.611   TM1.Process   Process "}bedrock.cube.data.copy":  finished with ProcessBreak

**Describe what's not working the way you expect.**
Didn't get the expected result? Describe:
1. I don't understand what I'm doing wrong wrt MSG:
ErrorMsg:An element start delimiter must follow a dimension name: -> (13)
2. Both V01->RY2019_4QOB_F are elements from dim kh_versi
MSG: rrorMsg:Element: kh_versi:V01 does not exist in dimension kh_bgkto

**Version**
- OS: Windows Server 2012 R2
- TM1 Server Version: PAL 2.0.7

**Comment by lotsaram** [comment]
In this case the [documentation](https://github.com/cubewise-code/bedrock/wiki/%7Dbedrock.cube.data.copy) and the error message are sufficient to explain.

The input to pEleMapping is malformed as it does not contain the element start delimiter.
pEleStartDelim="¦"
pEleMapping ="kh_versi:V01->RY2019_4QOB_F"

Either you need to change pEleStartDelim to ":" or else change the text in pEleMapping to use broken bar not colon.
