### ISSUE TITLE
}bedrock.hier.create.fromsubset fails if you are trying to copy a C element to a new hierarchy

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/bedrock#60]
**Describe the bug**
Trying to create a new hierarchy using a rollup fails. This happens when the process tries to insert a N element which already exists as a C element in a different hierarchy.

Is there any reason why we insert all elements as N into the target hierarchy? Line number here: https://github.com/cubewise-code/bedrock/blob/master/main/%7Dbedrock.hier.create.fromsubset.pro#L250

**To Reproduce**
1. Try to create a new hierarchy based on the T Year-Week dimension
2. Run the TI:  }bedrock.hier.create.fromrollup and select the rollup element as "Group YTG" as an example
3. See the error.

**Expected behavior**
Copying a rollup to a new hierarchy should not fail

**Screenshots**
N/A

**Version**
 - OS: Win 2012 R2
  - TM1 Server Version: 11.5.0.23

**Additional context**
N/A

**Comment by lotsaram** [comment]
fixed in #63
