### ISSUE TITLE
}bedrock.hier.create.fromsubset won't copy rollup from alt hierarchy to main or another alt hierarchy

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/bedrock#61]
**Describe the bug**
If you want to copy a rollup from an alternate hierarchy to the main hierarchy or another alternate hierarchy, the rollup won't be properly created.
The reason is that at line https://github.com/cubewise-code/bedrock/blob/master/main/%7Dbedrock.hier.create.fromsubset.pro#L246 we set the descendant attribute for the source hierarchy but at line https://github.com/cubewise-code/bedrock/blob/master/main/%7Dbedrock.hier.create.fromsubset.pro#L315 we always look at the main hierarchy. Therefore you won't be able to ever use a rollup or subet in an alternate hierarchy as a source.

**Solution:**
replace line https://github.com/cubewise-code/bedrock/blob/master/main/%7Dbedrock.hier.create.fromsubset.pro#L315 
with ```sDecendant = ElementAttrS(pSrcDim, pSrcHier, sElName, cHierAttr);```

**To Reproduce**
1. Have a dimension with multiple hierarchies
2. Try to copy a rollup from one of the hierarchies using }bedrock.hier.create.fromrollup either to a new hierarchy or to main one
3. Check the result and observe that the new rollup is completely broken.

**Expected behavior**
You should be able to copy a rollup from an alternate hierarchy

**Screenshots**

**Version**
 - OS: Win 2012 R2
  - TM1 Server Version: 11.5.0.23

**Additional context**

**Comment by lotsaram** [comment]
fixed in #63
