### ISSUE TITLE
Dimension clone does not copy rule calculated attributes

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/bedrock#64]
**Describe the bug**
Cloning a dimension with attributes doesn't copy the rule calculated attributes to the target dimension

**To Reproduce**
1. Setup a dimension with a rule calculated attribute
2. Clone the dimension using the }bedrock.dim.clone TI
3. See that the rule calculated attribute wasn't copied.

**Expected behavior**
Line https://github.com/cubewise-code/bedrock/blob/master/main/%7Dbedrock.dim.clone.pro#L298 should be ```If( CellIsUpdateable( sAttrTragetDim, vEle, sAttrName ) = 1 );```

**Version**
 - OS: Win 2012 R2
  - TM1 Server Version: 11.5

**Comment by lotsaram** [comment]
fixed in #67
