### ISSUE TITLE
}bedrock.hier.clone.pro might have bug with hierarchy unwind

### ISSUE THREAD

**Issue by janus-t** [cubewise-code/bedrock#91]
It seems that unwind process parameters are not working as intended in }bedrock.hier.clone.pro process. Unwind always targets default hierarchy (pTgtDim) instead of pTgtHier. Also, pConsol value '' means that }bedrock.hier.unwind doesn't seem to unwind. Value should probably be '*'.

```
### Create target dimension Hierarchy ###
If( HierarchyExists( pTgtDim, pTgtHier) = 0 );
    HierarchyCreate( pTgtDim, pTgtHier );
Else;
    IF(pUnwind = 1 );
      ExecuteProcess('}bedrock.hier.unwind',
        'pLogOutput', pLogOutput,
        'pDim', pTgtDim,
        'pHier', pTgtDim,
        **'pConsol', '',
        'pRecursive', 1**
        );
    ELSEIF(pUnwind = 2 );
      #Do nothing
    ELSEIF(pUnwind = 0 );
      HierarchyDeleteAllElements( pTgtDim, pTgtHier );
    EndIf;
EndIf;
```

**Comment by lotsaram** [comment]
Thanks for the catch @janus-t 
Yes it looks like there are some artifacts from the last v3 version in the ExecuteProcess call. Should be a simple fix.
