### ISSUE TITLE
}bedrock.hier.element.create - Error while adding element to a dimension without hierarchies

### ISSUE THREAD

**Issue by rycy85** [cubewise-code/bedrock#95]
**Describe the bug**
Process aborted while executing it on a dimension without hierarchies created
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/46925444/65894311-d4c26a80-e3a9-11e9-802d-11d77e71190d.png">

**To Reproduce**
1. Go to process }bedrock.hier.element.create
2. Run on a dimension w/t hierarchies
3. Result is process aborted
Error: Prolog procedure line (194): Dimension "}Hierarchies_}APQ Parameters" not found

**Expected behavior**
Create an element in the hierarchy.

**Version**
 - OS: Windows Server 2012
  - TM1 Server Version: 11.4

**Comment by lotsaram** [comment]
The error isn't on a dimension without hierarchies but a dimension without a }Hierarchies_dimName control dimension. Or in other words any control object dimension as these don't have }Hierarchies_ dimension created for them.
The check needs to be done on }Dimensions dimension looking for "dimName" element and "dimName:hierName" element and **not** in }Hierarchies_dimName
