### ISSUE TITLE
}bedrock.hier.unwind.pro - Unwind consolidations outside parameter pConsol (when pRecursive = 1)

### ISSUE THREAD

**Issue by JimmyKer** [cubewise-code/bedrock#98]
**Describe the bug**
When running a **Recursive** _unwind_ with parameter pConsol, is the child consolidation(s) that is used in a parallel hierarchie is also unwind. Although we have specified the pConsol parameter.
This worked perfect in v3.

**To Reproduce**
1. Use following TI to create the test Dimension 
```
pLogOutput = 0 ;
pDim = 'UNWIND_EXAMPLE' ;
DIMENSIONDESTROY(pDim);
DIMENSIONCREATE(pDim);
ExecuteProcess( '}bedrock.hier.element.create', 'pLogOutput', pLogOutput,
	    	'pDim', pDim, 'pHier', '', 'pEle', 'C_TOP1 & C_TOP2 & C_TOP3 & C_TOP_DEMO & TOP1_1 & TOP1_2 & TOP2_1 & TOP2_2 & TOP3_1 & TOP3_1',
	    	'pEleType', 'C', 'pInsertionPoint', '',
	    	'pDelim', '&'
		);
DIMENSIONELEMENTCOMPONENTADD(pDim,'C_TOP1','TOP1_1', 1);
DIMENSIONELEMENTCOMPONENTADD(pDim,'TOP1_1', 'A', 1);
DIMENSIONELEMENTCOMPONENTADD(pDim,'TOP1_1', 'B', 1);
DIMENSIONELEMENTCOMPONENTADD(pDim,'C_TOP1','TOP_CROSS', 1);
DIMENSIONELEMENTCOMPONENTADD(pDim,'TOP_CROSS', 'CROSS_A', 1);
DIMENSIONELEMENTCOMPONENTADD(pDim,'TOP_CROSS', 'CROSS_B', 1);

DIMENSIONELEMENTCOMPONENTADD(pDim,'C_TOP1','TOP1_2', 1);
DIMENSIONELEMENTCOMPONENTADD(pDim,'TOP1_2', 'C', 1);
DIMENSIONELEMENTCOMPONENTADD(pDim,'TOP1_2', 'D', 1);

DIMENSIONELEMENTCOMPONENTADD(pDim,'C_TOP2','TOP2_1', 1);
DIMENSIONELEMENTCOMPONENTADD(pDim,'C_TOP2','TOP2_2', 1);
DIMENSIONELEMENTCOMPONENTADD(pDim,'TOP2_1', 'E', 1);
DIMENSIONELEMENTCOMPONENTADD(pDim,'TOP2_1', 'F', 1);

DIMENSIONELEMENTCOMPONENTADD(pDim,'C_TOP3','TOP3_1', 1);
DIMENSIONELEMENTCOMPONENTADD(pDim,'TOP3_1', 'G', 1);
DIMENSIONELEMENTCOMPONENTADD(pDim,'C_TOP3','TOP3_2', 1);
DIMENSIONELEMENTCOMPONENTADD(pDim,'TOP3_2', 'H', 1);

DIMENSIONELEMENTCOMPONENTADD(pDim,'C_TOP_DEMO','TOP_CROSS', -1);
DIMENSIONSORTORDER(pDim,'','','BYHIERARCHY','ASCENDING');
```

2. Now when the TEST dimension is created, unwind the first 3 (level2) consolidations, using following TI:
```
pLogOutput = 0 ;
pDim = 'UNWIND_EXAMPLE' ;
 ExecuteProcess( '}bedrock.hier.unwind', 'pLogOutput', pLogOutput,
    	'pDim', pDim, 'pHier', '', 'pConsol', 'C_TOP1 & C_TOP2 & C_TOP3',
    	'pRecursive', 1, 'pDelim', '&'
	);
```
3. Result is, that the 4th consolidation C_TOP_DEMO is also unwind from TOP_CROSS.

**Expected behavior**
In the above example, the consolidation C_TOP_DEMO should left untouched.

**Version**
 - OS: Windows Server 2016, Windows 10
  - TM1 Server Version: 11.5.00000.23 (PA 2.0.7)

**Comment by lotsaram** [comment]
@JimmyKer yes I can confirm this as a bug.
Actually it is due to an enhancement #71 done a few months ago to increase the speed of unwind. It has the side-effect however in the case of multiple parentage that because the C element is *deleted and re-added* that it not only removes all children but also removed the element from all of it's parents. Shoud be easy enough to fix by adding a check for multiple parents and in that case do the old method of looping children to remove.
